import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import localFont from "next/font/local";

const Poppins = localFont({
  src: "./Poppins-Regular.ttf",
  display: "swap",
  variable: "--font-poppins",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${Poppins.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
